LinkShortening/Models/UrlPl.cs
namespace LinkShortening.Presentation.Models
{
    public class UrlPl
    {
        public int Id { get; set; }
        public string? LongUrl { get; set; }
        public string? ShortUrl { get; set; }
        public DateTime? Creation { get; set; }
        public int TransitionCount { get; set; }
    }
}

LinkShortening/Controllers/UrlController.cs
using AutoMapper;
using LinkShortening.Business.Interfaces;
using LinkShortening.Business.Models;
using Microsoft.AspNetCore.Mvc;
using LinkShortening.Presentation.Models;

namespace LinkShortening.Presentation.Controllers
{
    public class UrlController : Controller
    {
        private readonly IUrlService _homeService;
        private readonly IMapper _mapper;
        private readonly string _absoluteUri;

        public UrlController(IUrlService homeService, IMapper mapper, IConfiguration configuration, IHttpContextAccessor httpContextAccessor)
        {
            _homeService = homeService;
            _mapper = mapper;

            var request = httpContextAccessor.HttpContext.Request;
            _absoluteUri = request.Scheme + "://" + request.Host + "/";
        }
        public async Task<IActionResult> Index()
        {
            //В реальном проекте я брал бы данные с сервера постранично
            var data = await _homeService.GetDataAsync();
            var result = _mapper.Map<IEnumerable<UrlBl>, IEnumerable<UrlPl>>(data);

            return View((result, _absoluteUri));
        }

        [HttpGet]
        public async Task<IActionResult> EditCreatePressAsync(int id)
        {
            var data = await _homeService.GetEditPressAsync(id);
            return data != null ?
                View("EditCreate", (_mapper.Map<UrlBl, UrlPl>(data), _absoluteUri)) :
                View("EditCreate", (new UrlPl(), _absoluteUri));
        }

        [HttpPost]
        public async Task<IActionResult> OnCreateUpdateAsync(UrlPl urlPl)
        {
            if (urlPl?.LongUrl == null || !_homeService.IsUrl(urlPl.LongUrl))
                return BadRequest($"Получен некорректный URL: {urlPl?.LongUrl}");

            var result = await _homeService.OnCreateOrFindExistAsync(_mapper.Map<UrlPl, UrlBl>(urlPl));

            return result != null ? View("EditCreate", (_mapper.Map<UrlBl, UrlPl>(result), _absoluteUri)) :
                StatusCode(500, "Внутренняя ошибка сервера: сохранение не удалось.");
        }

        [HttpGet]
        public async Task<IActionResult> OnDeleteAsync(int id)
        {
            var success = await _homeService.OnDeleteAsync(id);
            return success ? RedirectToAction("Index") : StatusCode(500, "Внутренняя ошибка сервера: удаление не удалось.");
        }

        [HttpGet]
        public async Task<IActionResult> ShortUrlRequest(string shortUrl)
        {
            if (string.IsNullOrEmpty(shortUrl)) return BadRequest("Не корректная сокращенная ссылка");

            string fullUrl = await _homeService.GetLongUrlAndIncreaseCounter(shortUrl);

            return !string.IsNullOrEmpty(fullUrl) ? Redirect(fullUrl) : NotFound("Полный Url не найден в БД");
        }
    }
}

LinkShortening/Views/Home/Index.cshtml
@model IEnumerable<UrlPl>

<!DOCTYPE html>
<html>
<head>
    <title>Список ссылок</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center">Список ссылок</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Длинный URL</th>
                    <th scope="col">Сокращенный URL</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Количество переходов</th>
                    <td colspan="col">
                        <form method="get" action="/Home/CreatePress">
                            <button type="submit" class="btn btn-success">Создать</button>
                        </form>
                    </td>
                </tr>
            </thead>
            <tbody>
                @foreach (var link in Model)
                {
                    <tr>
                        <td><a href="@link.LongUrl">@link.LongUrl</a></td>
                        <td><a href="@link.ShortUrl">@link.ShortUrl</a></td>
                        <td>@link.Creation</td>
                        <td>@link.TransitionCount</td>
                        <td>
                            <form method="get" action="/Home/EditPress/@link.Id">
                                <button type="submit" class="btn btn-primary">Редактировать</button>
                            </form>
                        </td>
                        <td>
                            <form method="get" action="/Home/OnDelete/@link.Id" onsubmit="return confirmDelete()">
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function confirmDelete() {
            return confirm("Вы уверены, что хотите удалить эту ссылку?");
        }
    </script>

</body>
</html>

LinkShortening/Views/Shared/_Layout.cshtml
@RenderBody()

LinkShortening/Views/Url/EditCreate.cshtml
@model (UrlPl Link, string Adress);

<!DOCTYPE html>
<html>
<head>
    <title>Создание/редактирование ссылки</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .btn {
            width: 150px;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center">Создание/редактирование ссылки</h1>
        <form id="urlForm" method="post" action="@Url.Action("OnCreateUpdate", "Url")" onsubmit="return validateUrl()">
            <input type="hidden" id="id" name="id" value="@Model.Link.Id">
            <div class="mb-3">
                <label for="longUrl" class="form-label">Длинный URL</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="longUrl" name="longUrl" value="@Model.Link.LongUrl">
                    <button type="submit" class="btn btn-primary" id="shortenButton">Сократить</button>
                </div>
            </div>
            @if (!string.IsNullOrEmpty(Model.Link.ShortUrl))
            {
                <div class="mb-3">
                    <label for="shortUrl" class="form-label">Сокращенная ссылка</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="shortUrl" name="shortUrl" value="@Model.Adress@Model.Link.ShortUrl" readonly>
                        <button type="button" class="btn btn-primary" id="copyButton" onclick="copyShortUrl()">Копировать</button>
                    </div>
                </div>
            }
        </form>
        <a href="/Url/Index" class="btn btn-secondary">Вернуться</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    <script>
        function copyShortUrl() {
            var shortUrlInput = document.getElementById('shortUrl');
            shortUrlInput.select();
            document.execCommand('copy');

            var copyButton = document.getElementById('copyButton');
            copyButton.textContent = 'Скопировано';
            copyButton.style.backgroundColor = 'green';
        }

        function validateUrl() {
            var urlInput = document.getElementById('longUrl');
            var urlValue = urlInput.value.trim();
            var urlPattern = /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i;

            if (!urlPattern.test(urlValue)) {
                alert("Введен некорректный URL");
                return false;
            }
        }
    </script>
</body>
</html>

LinkShortening/Views/Url/Index.cshtml
@model (IEnumerable<UrlPl> Links, string Adress)

<!DOCTYPE html>
<html>
<head>
    <title>Список ссылок</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .url-cell {
            max-width: 15vw;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center">Список ссылок</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Длинный URL</th>
                    <th scope="col">Сокращенный URL</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Количество переходов</th>
                    <th scope="col">
                        <form method="get" action="/Url/EditCreatePress">
                            <button type="submit" class="btn btn-success">Создать</button>
                        </form>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var link in Model.Links)
                {
                    <tr>
                        <td class="url-cell">@link.LongUrl</td>
                        <td class="url-cell"><a href="@Model.Adress@link.ShortUrl" target="_blank">@Model.Adress@link.ShortUrl</a></td>
                        <td>@link.Creation</td>
                        <td>@link.TransitionCount</td>
                        <td>
                            <form method="get" action="/Url/EditCreatePress/@link.Id">
                                <button type="submit" class="btn btn-primary">Редактировать</button>
                            </form>
                        </td>
                        <td>
                            <form method="get" action="/Url/OnDelete/@link.Id" onsubmit="return confirmDelete()">
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function confirmDelete() {
            return confirm("Вы уверены, что хотите удалить эту ссылку?");
        }
    </script>

</body>
</html>